
study_accession: PRJEB4352
input_ena_table: /vortexfs1/omics/alexander/data/TARA/test_data/test_PRJEB4352.txt
inputDIR: /vortexfs1/omics/alexander/data/TARA/test_data
outputDIR: /vortexfs1/omics/alexander/data/TARA/test_data/output
scratch:  /vortexfs1/scratch/halexander
adapters: input/adapters/illumina-adapters.fa    
sample_list: input/Samplelist_forassembly.txt
sample_sets: ["MS-all-SRF-0.8-5.00"]
