study_accession: PRJEB4352
input_ena_table: /vortexfs1/omics/alexander/data/TARA/test_data/test_PRJEB4352.txt
inputDIR: /vortexfs1/omics/alexander/data/TARA/test_data
outputDIR: /vortexfs1/omics/alexander/data/TARA/test_data/output
scratch:  /vortexfs1/scratch/halexander
adapters: /vortexfs1/omics/alexander/shu/tara-euk-metaG/illumina-adapters.fa
restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
rerun-incomplete: true
keep-going: true
